name: CI

on:
  push:
    branches:
      - lab-2
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck
      - name: Run linter
        run: cppcheck --enable=all --inconclusive --error-exitcode=1 --suppress=missingIncludeSystem --quiet --force .

  format:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install clang-format
        run: choco install llvm -y
      - name: Run formatter
        run: clang-format --dry-run --Werror *.c
